def allPhrases():
    phrases = [
        "bastard",
        "damn...",
        "murdaaaaa",
        "murda shmurda",
        "ayee kristina",
        "ayee leonaaa",
        "damn... my guy",
        "bruh...",
        "leshgoooo",
        "tourney?",
        "shiiiiiii",
        "noice",
        "aight cool",    
        "cool",
        "?",
        "...",
        "yo?",
        "sheesh",
        "..?",
        "2's club",
        "jump on RL?",
        "latas",
        "turn on server?",
        "HAHA",
        "HAHAHA",
        "gym?",
        "hop on acad?",
        "algds",
        "aight",
        "cap",
        ]

    out_of_context = [
        "yo my friend said these controls for PS4 are easier what do u think?",
        #"let me guess Elise still hates my guts to the point of no return?",
        "yo bigger nonces?",
        "u moving mad bruh",
        "am i your first child?",
        "<@706661660638838865> you skux",
        "😐  you have a son..... called <@694382869367226368>..... who you are putting up for adoption",
        "Yo The Riddler doesn't know who the Batman is",
        "damn she just roasted and annihilated me and gave 0 sympathy",
        "true im still growin",
        "Yo I did the Rataalada",
        "I JUST GRINDED 2V2 COMP, SCORED AND WON EVERY GAME, IM DIAMOND 2 DIV 1",
        "If you haven't learnt it, then you have learnt that you haven't learnt that you've learnt it",
        "damn well we dont really know that I know that you know",
        "I got Z now, goodluck for u guys",
        "yo whats the house number",
        "<@238063640601821185> I cant join the server",
        "i heard murder and came running",
        "yo. there has been a tech difficulty with my bookshelf door, need you to fix later when u come on",
        "CONOR BOI U BLUE BASTARD",
        "the hand goes into something, and murder",
        "light mode is god mode, how do i get mine to light mode?",
        "Did CONORU THE KANGAROO VIOLATE my guy, This Bugalug",
        "AFUCKA YOUS",
        "imagine imagining",
        "murda to my face",
        "you can't take my job then I'll be... without a job",
        "yo jeez slavery gaddamn",
        "💀 dead",
        "you need Jesus Christ rn",
        "Because I'm already black",
        "YO CAN YOU GUYS HEAR ME ON DISCORD?",
        "ok ok ok ok ok ok ok ok ok ok ok ok ok",
        "Can i get an.. OWA OWA!?",
        "😱 HELP ME SOMEBODY, <@288884848012296202> GONNA GUN ME DOWN FROM A HELI",
        "OMG WHAT A SOLAR NUKE!?!?",
        "Because.... if I dont get an OWA OWAA from you...\nI will die of a heart attack",
        "HELIKOPTER HELIKOPTER!!!",
        "hope you lose WAAAHHHH",
        "i gotta practice my evasional techniques",
        "I have a dream that one day every valley shall be exalted,\nand every hill and mountain shall be made low,\nthe rough places will be made plain,\nand the crooked places will be made straight",
        "🤣🤣🤣🤣🤣🤣🤣",
        "i hate this bugalug, kick him",
        ]
    return phrases, out_of_context
